# Generated by Django 4.2.7 on 2023-12-15 02:18

import apps.product.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=64)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('purchase_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('sale_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('expiration', models.DateField(validators=[apps.product.models.validate_future_date])),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=64)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('purchase_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('sale_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('expiration', models.DateField(validators=[apps.product.models.validate_future_date])),
            ],
        ),
        migrations.CreateModel(
            name='ProductExpirationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('expiration', models.DateField(validators=[apps.product.models.validate_future_date])),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product')),
            ],
        ),
    ]
