# Generated by Django 4.2.7 on 2023-12-23 13:05

import apps.product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='product',
            name='expiration',
            field=models.DateField(blank=True, null=True, validators=[apps.product.models.validate_future_date]),
        ),
        migrations.AlterField(
            model_name='productlog',
            name='expiration',
            field=models.DateField(blank=True, null=True, validators=[apps.product.models.validate_future_date]),
        ),
    ]
