# Generated by Django 4.2.7 on 2023-12-29 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_options_alter_product_expiration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productexpirationlog',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
