# Generated by Django 4.2.7 on 2023-12-11 23:13

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiration',
            field=models.DateField(validators=[app.models.validate_future_date]),
        ),
    ]
