# Generated by Django 4.2.7 on 2023-11-29 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_purchase_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='app.logproduct'),
        ),
    ]
