# Generated by Django 4.2.7 on 2023-11-29 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_purchase_log_products_alter_purchase_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='products',
        ),
    ]
