# Generated by Django 4.2.7 on 2023-12-01 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_logproduct_brand_alter_logproduct_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='total_price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
