# Generated by Django 4.2.7 on 2023-12-03 19:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_purchase_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logproduct',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
